name: Blot
description: Teens make art and get a Blot
maintainers: [leo, shawn, kara]
channels:
  - name: blot
    id: C04GCH8A91D
repos:
  - uri: https://github.com/hackclub/blot
resources:
  - name: github
    uri: https://github.com/hackclub/blot
