name: DNS
description: DNS stuff for Hack Club
slack-managers: [U014ND5P1N2, U04QH1TTMBP, USNPNJXNX, U0C7B14Q3, U013B6CPV62]
maintainers: [faisalsayed10, grymmy, sampoder, maxwofford, cjdenio]
slack-channels:
  - name: dns
    id: CS8TQ86GN
    sla:
      responseTime: 1h
repos:
  - uri: https://github.com/hackclub/dns
    sla:
      responseTime: 1h
