name: HQ Engineering
description: HQ Engineering stuff for Hack Club
maintainers: [faisal, graham, josias]
channels:
  - name: infra-alerts
    id: C05G25Y9M6V
    sla:
      responseTime: 1h
  - name: hq-engineering
    id: C05SVRTCDGV
    sla:
      responseTime: 1h
repos:
  - uri: https://github.com/hackclub/slacker
    sla:
      responseTime: 1h
  - uri: https://github.com/hackclub/infra
    sla:
      responseTime: 1h
  - uri: https://github.com/hackclub/global
    sla:
      responseTime: 1h
