name: HQ Engineering
description: HQ Engineering stuff for Hack Club
maintainers: [faisal, graham, josias, marios]
clawback: true
grouping:
  minutes: 10
channels:
  - name: infra-alerts
    id: C05G25Y9M6V
    sla:
      responseTime: 1h
  - name: hq-engineering
    id: C05SVRTCDGV
    sla:
      responseTime: 1h
repos:
  - uri: https://github.com/hackclub/slacker
    sla:
      responseTime: 1h
  - uri: https://github.com/hackclub/infra
    sla:
      responseTime: 1h
  - uri: https://github.com/hackclub/global
    sla:
      responseTime: 1h
resources:
  - name: hq-eng-slack-channel
    uri: https://hackclub.slack.com/archives/C05SVRTCDGV
  - name: grafana
    uri: https://telemetry.hackclub.com
  - name: heroku
    uri: https://dashboard.heroku.com
  - name: digitalocean
    uri: https://www.digitalocean.com
  - name: dashboard-slacker
    uri: https://telemetry.hackclub.com/d/fe0c8789-033d-4add-9cd6-6e38a4d2bde6/slacker?orgId=1
  - name: alerts-slack-channel
    uri: https://hackclub.slack.com/archives/C05G25Y9M6V
