name: hack.af
description: Hack Club URL infrastructure
slack-managers: [U014ND5P1N2, U04QH1TTMBP, U01PJ08PR7S, U0C7B14Q3]
maintainers: [faisalsayed10, grymmy, JosiasAurel, maxwofford]
slack-channels:
repos:
  - uri: https://github.com/hackclub/hack.af
    sla:
      responseTime: 1h
