name: Leaders
description: Place where leaders get help
maintainers: [thomas, arpan, sahiti, jasper]
channels:
  - name: leaders
    id: C02PA5G01ND
  - name: application-conspiracy
    id: C02F9GD407J
repos:
  - uri: https://github.com/hackclub/jams
    sla:
      responseTime: 48h
  - uri: https://github.com/hackclub/toolbox
    sla:
      responseTime: 48h
