name: Onboard
description: Teens make a PCB for $100 and get it shipped for free
maintainers: [prophetorpheus, max]
channels:
  - name: onboard
    id: C056AMWSFKJ
  - name: onboard-bts
    id: C05AB4G6PPV
  - name: onboard-help
    id: C0593MG26TT
  - name: onboard-grant-requests
    id: C063HR4LB4H
repos:
  - uri: https://github.com/hackclub/onboard
sections:
  - name: grants
    pattern: A new Onboard grant has been requested
