---
name: Pizza
description: Pizza for everyone!
maintainers: [thomas, arpan, sahiti, jasper]
channels:
  - name: pizza-party
    id: C05RZ6K7RS5
  - name: pizza-grant-approval
    id: C05RZATA3QR
  - name: pizza-grant-renewal
    id: C06HR3TE6TA
  - name: pizza-pizza
    id: C06H2A574FL
  - name: pizza-queries
    id: C063JHFQV1S
  - name: pizza-dev
    id: C06CR1YQQAV
repos:
  - uri: https://github.com/hackclub/pizza-fund
sections:
  - name: india
    pattern: india
