name: Scrapbook
description: Hack Club Scrapbook infrastructure
maintainers: [graham, josias]
repos:
  - uri: https://github.com/hackclub/scrappy
    sla:
      responseTime: 1h
  - uri: https://github.com/hackclub/scrapbook
    sla:
      responseTime: 1h
