name: Sinerider
description: A game about math and graphing!
maintainers: [chris, elliot, graham]
channels:
  - name: gamedev
    id: C6LHL48G2
    sla:
      responseTime: 1h
repos:
  - uri: https://github.com/hackclub/sinerider
    sla:
      responseTime: 1h
