name: Slash Z
description: Hack Club zoooom infrastructure
slack-managers: [U014ND5P1N2, U04QH1TTMBP, U01PJ08PR7S, U0C7B14Q3]
maintainers: [faisalsayed10, grymmy, JosiasAurel, maxwofford]
slack-channels:
  - name: development-of-slash-z
    id: C0179FFFRRV
    sla:
      responseTime: 1h
repos:
  - uri: https://github.com/hackclub/slash-z
    sla:
      responseTime: 1h

repos:
hackaf
