name: Sprig
description: Teens make games and get a Sprig
maintainers: [leo, lucas, kognise, max, graham, josias, shawn, hugo]
channels:
  - name: sprig
    id: C02UN35M7LG
    sla:
      responseTime: 1h
  - name: sprig-platform
    id: C04S1A8NT44
    sla:
      responseTime: 24h
  - name: sprig-device-requests
    id: C063DFZ532M
    sla:
      responseTime: 24h
repos:
  - uri: https://github.com/hackclub/sprig
    sla:
      responseTime: 1h
    owners:
      default: [lucas]
      subsections:
        - owners: [lucas]
          pattern: What is your game about\?
  - uri: https://github.com/hackclub/spade
    sla:
      responseTime: 24h
resources:
  - name: github
    uri: https://github.com/hackclub/sprig
  - name: dashboard
    uri: https://telemetry.hackclub.com/d/b7ac7960-a18f-4c83-a4e5-767d50ad62c7/sprig?orgId=1
  - name: vercel
    uri: https://vercel.com/hackclub/sprig
  - name: website
    uri: https://sprig.hackclub.com
  - name: editor
    uri: https://sprig.hackclub.com/editor
