name: Sprig
description: Teens make games and get a Sprig
slack-managers: [UR6P49Q79, U04QH1TTMBP, U01PJ08PR7S, U022FMN61SB, U04BBP8H9FA]
maintainers: [faisalsayed10]
slack-channels:
  - name: sprig
    id: C02UN35M7LG
    sla:
      responseTime: 1h
  - name: sprig-platform
    id: C04S1A8NT44
    sla:
      responseTime: 24h
repos:
  - uri: https://github.com/hackclub/sprig
    sla:
      responseTime: 1h
  - uri: https://github.com/hackclub/spade
    sla:
      responseTime: 24h
