name: Sprig
description: Teens make games and get a Sprig
slack-managers: [UR6P49Q79, U04QH1TTMBP, U01PJ08PR7S, U022FMN61SB, U04BBP8H9FA]
maintainers: [faisalsayed10, grymmy]
slack-channels:
  - name: bot-spam
    id: C0P5NE354
    sla:
      responseTime: 24h
repos:
  - uri: https://github.com/hackclub/sprig
    sla:
      responseTime: 1h
